<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width,initial-scale=1.0">
        <title>Mon parcours</title>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        <link rel="stylesheet" href="css/style.css">
        <link rel="stylesheet" href="css/<?= $view ?>.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
        <script src="https://kit.fontawesome.com/f6ab443034.js" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    </head>
    <body>
        <header>
            <div id="toggle-parent">
                <div id="toggle">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                  </div>
            </div>
            <div id="menu" class="menu-off fade-out">
                <ul>
                    <a href="index.php?parcours">
                        <li>Mon parcours</li>
                    </a>
                    <a href="index.php?projects">
                        <li>Projets</li>
                    </a>
                    <a href="index.php?interets">
                        <li>Intérets</li>
                    </a>
                    <a href="index.php?contact">
                        <li>Me contacter</li>
                    </a>
                </ul>
            </div>
            <?php if($view === "parcours"): ?>
                <h1 class="fade-in content"><span class="display"></span></h1>
                <q class="content">Développeur Intégrateur Web</q>
                <img class="fade-in content" src="images/119210662_2629684977269470_2346559317229668440_n.jpg" alt="photo vincent spire">
            <?php endif; ?> 
        </header>
        <main class="hide">
            <?php include "views/".$view.".html" ?>
        </main>
        <?php if($view !== 'contact'): ?>
            <script src="js/<?= $view ?>.js"></script>
        <?php endif; ?>
        <script src="js/p-menu.js"></script>
    </body>
</html>